### ISSUE TITLE
"Deposit Anywhere" feature request

### ISSUE THREAD

**Issue by Frost212** [Torphedo/Shipbreaker-Cheats#2]
Hello, first, thank you for making this. Second would it be possible to grant the ability to deposit items anywhere and still receive full credit? There was an old cheat engine table that used to do this but none of the other mods/trainers/tables i have found seem to have this behavior.

**Comment by kadirnanish** [comment]
https://github.com/Torphedo/BOTW-Mods/issues/2#issue-1007656189

**Comment by kadirnanish** [comment]
https://github.com/Torphedo/BOTW-Mods/issues/2#issue-1007656189

**Comment by kadirnanish** [comment]
https://github.com/Torphedo/Shipbreaker-Cheats/issues/2#issue-1028069907

**Comment by kadirnanish** [comment]
https://github.com/Torphedo/Shipbreaker-Cheats/issues/2#issue-1028069907

**Comment by zer0blivion** [comment]
I second this suggestion.

**Comment by XeonDead** [comment]
Old cheat table to enable such behaviour should still work. You can find the table on fearlessrevolution.com.

**Comment by Torphedo** [comment]
Implemented in the latest release of the [BepInEx port](https://github.com/Torphedo/shipbreaker-cheats-1/releases/tag/0.8.1).
