### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by Glitched-Fox-Studios** [Torphedo/Shipbreaker-Cheats#4]
1.0 came out today and I can confirm that this no longer works. When starting game, all you get is a black screen,

**Comment by Torphedo** [comment]
Yes, it has to be manually updated whenever the game gets updated. They made a lot of changes for 1.0, so it'll probably take longer this time. The main issue is that my code to check for RACE mode no longer works, so I have to figure out how to do it again (usually I can  just copy/paste)

**Comment by Torphedo** [comment]
Forgot to post here, but the 1.0 port can be found at [https://github.com/Torphedo/shipbreaker-cheats-1](https://github.com/Torphedo/shipbreaker-cheats-1).  Everything except the keybinds are working again.
